name: "Validations"
on:
  push:
    branches:
      - main
  pull_request:

jobs:

  Static-Analysis:
    name: "Static analysis"
    runs-on: ubuntu-22.04
    steps:
    - name: Bootstrap environment
      uses: anchore/go-make/.github/actions/bootstrap@latest

    - name: Run static analysis
      run: make static-analysis

  Unit-Test:
    name: "Unit tests"
    runs-on: ubuntu-22.04
    steps:
      - name: Bootstrap environment
        uses: anchore/go-make/.github/actions/bootstrap@latest

      - name: Run unit tests
        run: make unit
